/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Yoandry
 */
public class Inicial extends javax.swing.JFrame {

    /**
     * Creates new form Inicial
     */
    public Inicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bkInicial = new javax.swing.JPanel();
        bk2Inicial = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btMateriaPrima1 = new javax.swing.JButton();
        btMateriaPrima2 = new javax.swing.JButton();
        btProductosTerminados = new javax.swing.JButton();
        btProveedores = new javax.swing.JButton();
        btGerente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modulo_Bodega");
        setResizable(false);

        bkInicial.setBackground(new java.awt.Color(255, 255, 255));

        bk2Inicial.setBackground(new java.awt.Color(0, 204, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Modulo Bodega");

        javax.swing.GroupLayout bk2InicialLayout = new javax.swing.GroupLayout(bk2Inicial);
        bk2Inicial.setLayout(bk2InicialLayout);
        bk2InicialLayout.setHorizontalGroup(
            bk2InicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bk2InicialLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        bk2InicialLayout.setVerticalGroup(
            bk2InicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bk2InicialLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btMateriaPrima1.setText("Gestion Materia Prima 1");
        btMateriaPrima1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMateriaPrima1ActionPerformed(evt);
            }
        });

        btMateriaPrima2.setText("Gestion Materia Prima 2");
        btMateriaPrima2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMateriaPrima2ActionPerformed(evt);
            }
        });

        btProductosTerminados.setText("Gestion Productos Terminados");
        btProductosTerminados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProductosTerminadosActionPerformed(evt);
            }
        });

        btProveedores.setText("Gestion Proveedores");
        btProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProveedoresActionPerformed(evt);
            }
        });

        btGerente.setText("Gestion Gerente");
        btGerente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGerenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bkInicialLayout = new javax.swing.GroupLayout(bkInicial);
        bkInicial.setLayout(bkInicialLayout);
        bkInicialLayout.setHorizontalGroup(
            bkInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bkInicialLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(bkInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btMateriaPrima2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btProductosTerminados, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                    .addComponent(btMateriaPrima1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btGerente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(bk2Inicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bkInicialLayout.setVerticalGroup(
            bkInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bk2Inicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bkInicialLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(btMateriaPrima1)
                .addGap(39, 39, 39)
                .addComponent(btMateriaPrima2)
                .addGap(40, 40, 40)
                .addComponent(btProductosTerminados)
                .addGap(40, 40, 40)
                .addComponent(btProveedores)
                .addGap(40, 40, 40)
                .addComponent(btGerente)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bkInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bkInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btMateriaPrima1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMateriaPrima1ActionPerformed
        Gestion_MateriaPrima1 a = new Gestion_MateriaPrima1();
        a.setVisible(true);
        a.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btMateriaPrima1ActionPerformed

    private void btMateriaPrima2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMateriaPrima2ActionPerformed
        Gestion_MateriaPrima2 a = new Gestion_MateriaPrima2();
        a.setVisible(true);
        a.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btMateriaPrima2ActionPerformed

    private void btProductosTerminadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProductosTerminadosActionPerformed
        Gestion_ProductosTerminados a = new Gestion_ProductosTerminados();
        a.setVisible(true);
        a.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btProductosTerminadosActionPerformed

    private void btProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProveedoresActionPerformed
        Gestion_Proveedor a = new Gestion_Proveedor();
        a.setVisible(true);
        a.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btProveedoresActionPerformed

    private void btGerenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGerenteActionPerformed
        Gestion_Gerente a = new Gestion_Gerente();
        a.setVisible(true);
        a.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btGerenteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bk2Inicial;
    private javax.swing.JPanel bkInicial;
    private javax.swing.JButton btGerente;
    private javax.swing.JButton btMateriaPrima1;
    private javax.swing.JButton btMateriaPrima2;
    private javax.swing.JButton btProductosTerminados;
    private javax.swing.JButton btProveedores;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
