@startuml yoandry

class Empresa {
  -nombreEmpresa: string
  -direccionEmpresa: string
  -numeroTelefonoEmpresa: string
  +Empresa(): void
}

class Obrero {
  -idO: string
  -nombreO: string
  +Obrero(): void
  +Fundir(): void
  +Cargar(): void
}

class AreaDeTrabajo {
  -numeroA: string
  -nombreA: string
  -direccionA: string
  +AreaDeTrabajo(): void
}

class Metalmecanica {
  -cantidadObreros: int
  ingenieroACargo: string
  +Metalmecanica(): void
}

class FundicionHormigon {
  -cantidadFundidores: int
  ingenieroACargo: string
  +FundicionHormigon(): void
}

class ProcesoProductivo {
  -tipoPProductivo: string
  -inicioPProductivo: string
  -finPProductivo: string
  +ProcesoProductivo(): void
}

class MateriaPrima1 {
  +MateriaPrima1(): void
}

class MateriaPrima2 {
  +MateriaPrima2(): void
}

class Bodega {
  -nombreB: string
  -cantEstibas: int
  -cantTrabajadores: int
  -tipoMateriaP: string
  +Bodega(): void
}

class ProductoTerminado {
  -cantPTerminados: int
  +ProductosTerminados(): void
}

class Producto {
  -nombreProducto: string
  -precioCompra: double
  -precioVenta: int
  -calidadProducto: string
  +Producto(): void
}

class ProductoEstandar {
  -idPEstandar: string
  +ProductoEstandar(): void
}

class ProductoPersonalizado {
  -idPPersonalizado: string
  +ProductoPersonalizado(): void
}

class Proveedor {
  -idProveedor: string
  -nombreProveedor: string
  -numeroTelefonoProveedor: string
  +Proveedor(): void
}

class Pedido{
-idCliente:string
-fechaPedido:string
-costoEntrega:int
+Pedido():void
}

class Gerente {
  -idGerente: string
  -nombreGerente: string
  -numeroTelefonoGerente: string
  +Gerente(): void
}

Empresa "1" --o "1...*" Obrero : Tiene
Empresa "1" --o "1...*" AreaDeTrabajo : Posee
Empresa "1" --o "1" Gerente : Tiene

AreaDeTrabajo "1" --o "1...8" Obrero : Trabaja

AreaDeTrabajo "1" --o "1...*" Metalmecanica : Pertenece
AreaDeTrabajo "1" --o "1...*" FundicionHormigon : Pertenece

Metalmecanica "1" --o "1...*" ProcesoProductivo : Tiene
FundicionHormigon "1" --o "1...*" ProcesoProductivo : Tiene

ProcesoProductivo "1" --o "1...*" MateriaPrima1 : Utiliza
ProcesoProductivo "1" --o "1...*" MateriaPrima2 : Utiliza

MateriaPrima1 "1...*" --o "1...*" Bodega : Encuentra
MateriaPrima2 "1...*" --o "1...*" Bodega : Encuentra

ProductoTerminado "1" --o "1" Bodega : Guarda

Producto "1" --o "1" ProcesoProductivo : Posee

Producto "1" --o "1" ProductoTerminado : Transporta

Pedido "1" --o "1...*" Producto : Contiene

ProductoEstandar "1" --o "1" Producto : Pertenece

ProductoPersonalizado "1" --o "1" Producto : Pertenece

Cliente "1" --o "1...*" Pedido : Realiza

@enduml


